#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status

if [[ -n "${DRAEM_DEBUG}" ]]; then
    set -x
fi

# Load environment variables
source "$(dirname "$0")/env"

# Function to show usage instructions
function usage() {
    echo -n \
        "Usage: $(basename "$0")\n
Run a console in a docker container with all prerequisites installed.\n"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker run --rm -it --gpus all \
        --ipc=host \
        -v /home/serg3401/DEV/DRAEM/DATASETS:/DRAEM/DATASETS \
        -v /home/serg3401/DEV/DRAEM:/DRAEM \
        -p 8888:8888 \
        --entrypoint /bin/bash \
        draem_image:local
fi
